### ISSUE TITLE
[Question] Custom includes for test suites?

### ISSUE THREAD

**Issue by daniel-beard** [Quick/Quick#1067]
Hi, I'm using KIF+Quick for some tests in a monorepo where some modules use bare XCTest and some are using KIF+Quick.
These test suites have grown pretty huge, so for the bare XCTest modules, I've started using `xcodebuild`'s ability to only run an opt-in list of tests which gives me the ability to dynamically split our test suites across N build machines at build time.

I would like to use a similar approach for the KIF+Quick tests, but so far haven't been able to figure out a way to do this. Ideally, it would be something like:

```
- Introspect registered test cases at runtime (before running anything)
- Use custom split algorithm
- Set tests to run as an include list
- Run tests
```

Can anyone point me in the right direction here? I don't want to have to rewrite all these tests.

**Comment by jessesquires** [comment]
Hey there! 👋🏼 

I'm a new maintainer for this project and I'm trying to get the next release out ASAP and also clean up old issues and old PRs. I'm closing all issues that no longer seem relevant or are very old / stale.

This **does not** mean this issue is necessarily being rejected. If you are still interested in contributing the changes specified in this issue, please comment to request it be reopened.

We appreciate you opening this issue and acknowledge the time and effort you put in to contribute! You're awesome. 💯 However, we are all volunteers here with limited capacity working for free. Unfortunately, that means we must close out stale issues and PRs to move the project forward in a reasonable way.

We apologize for the inconvenience and appreciate your understanding! 😎 ✌🏼
