### ISSUE TITLE
Can't Override Method Spec()

### ISSUE THREAD

**Issue by zardasht-jazaa** [Quick/Quick#1266]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

import Nimble
import Quick

    final class Channel8Spec: QuickSpec {

    override func spec() {
        test_HelloWorld()
    }

    func test_HelloWorld() {
        
    }
}

### Environment

 - Quick: *7.4.0*
 - Nimble: *12.3.0*
 - Xcode Version: *15.1
 - Swift Version: *5.9*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:
 - Swift Package Manager *5.9.0*
![Screenshot 2024-01-29 at 2 34 56 PM](https://github.com/Quick/Quick/assets/141743367/4c2a0dbc-1797-445c-9308-395a620d1433)

**Comment by younata** [comment]
[Quick 7 changed spec to be a class function](https://github.com/Quick/Quick/releases/tag/v7.0.0).

**Comment by zardasht-jazaa** [comment]
Thanks for your Response Younata , after that change , no more Test Indicator On the test_HelloWord() appear! ,  I can't test the function separately!

**Comment by younata** [comment]
Oh, that's why you have that odd pattern.

Don't do that, that defeats the entire purpose of using Quick and you end up running the same test twice when you run all tests in Quick. We have [focusing](https://github.com/Quick/Quick/blob/main/Documentation/en-us/QuickExamplesAndGroups.md#temporarily-running-a-subset-of-focused-examples) for a reason, though it sadly does require you to recompile tests.
