### ISSUE TITLE
Troubles with Xcode's in-gutter test run button

### ISSUE THREAD

**Issue by kastiglione** [Quick/Quick#221]
I've been seeing sporadic behavior with the run button Xcode provides in the gutter. Sometimes it runs just the one spec, but a lot of times it runs the entire test suite. I've been running into this in ReactiveCocoa, so that's the only reproducing repo I can suggest.

Alternatively, I'd be happy to have a way to do focused tests, as discussed in #134.

**Comment by modocache** [comment]
If you use Specta or Quick and are disappointed with tests disappearing in Xcode's Test Navigator, tests lingering in the Test Navigator despite no longer being defined, or even tests not being run, please read and duplicate this radar: https://openradar.appspot.com/26028557.

Xcode does not provide the Specta or Quick maintainers with an API to address these problems. The best way to contribute to fixing these issues is to communicate to the Apple XCTest team that this is a use case we wish they'd support better. The best way I know to do that is to ask you all to re-submit https://openradar.appspot.com/26028557. 🙇

**Comment by johnendres** [comment]
Anything on having it not run all the tests no matter what?  We have some tests that are standard XCTest cases, and running one from the gutter still runs all the tests in that file.  Having to change the name of the test case to avoid it being run has caused people to forget to fix it before committing, and it can be overlooked in a code review.  Xcode 9, 10, and 11 so far.

**Comment by jessesquires** [comment]
Hey there! 👋🏼 

I'm a new maintainer for this project and I'm trying to get the next release out ASAP and also clean up old issues and old PRs. I'm closing all issues that no longer seem relevant or are very old / stale.

This **does not** mean this issue is necessarily being rejected. If you are still interested in contributing the changes specified in this issue, please comment to request it be reopened.

We appreciate you opening this issue and acknowledge the time and effort you put in to contribute! You're awesome. 💯 However, we are all volunteers here with limited capacity working for free. Unfortunately, that means we must close out stale issues and PRs to move the project forward in a reasonable way.

We apologize for the inconvenience and appreciate your understanding! 😎 ✌🏼
