### ISSUE TITLE
Update Quick CocoaPod to v0.3.0

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#246]
If there's a way to specify what version of Xcode/Swift a version supports, make sure that v0.3.0 is marked as only supporting Xcode 6.3/Swift 1.2.

/cc @ashfurrow :question:

**Comment by ashfurrow** [comment]
As far as I know, there is no minimum Swift version you can specify. What I believe we should do, and @mrackwitz can correct me here, is to set the minimum deployment target to something that only the new version of Xcode supports. This would prevent someone from building with an explicit error message describing the problem. 

However, you won't be able to push to CocoaPods trunk. Podfiles would look like this:

```swift
pod 'Quick', :git => "https://github.com/Quick/Quick.git"
```

**Comment by jshier** [comment]
While doing it this way requires Xcode 6.3, it's not a real requirement for Swift 1.2. Apps built with the iOS 8.3 SDK and Swift 1.2 using Xcode 6.3 work just fine on shipping iOS 8.1.3 devices (at least in my limited testing, like launch and navigation) since the Swift runtime is embedded in the built application. Setting an 8.3 deployment target will prevent these apps from running on older iOS versions for no reason.

**Comment by modocache** [comment]
Oops, this issue is obsolete--v0.3.0 was tagged a while ago! :bulb: 

If anyone has concerns with the current podspec please create a new issue. :+1:
