### ISSUE TITLE
Error: "Could not build Objective-C module 'Quick'"

### ISSUE THREAD

**Issue by sundeepgupta** [Quick/Quick#262]
I'm getting this error strangely because a couple of days ago, everything was fine. 

I have virtually a brand new project with the following Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target :butterflyTests do
	use_frameworks!
    pod 'Quick', :head
    pod 'Nimble', :head
end
```

And here is my only spec:

```
import Quick // Error on this line
import Nimble

class EntryVcSpec: QuickSpec {
    override func spec() {
        it("foo") {
            expect(false).to(beTruthy())
        }
    }
}
```

**Comment by modocache** [comment]
Hmm, that's troublesome. Can you try the following?

- Delete derived data and try building again. Hopefully this fixes your issue.
- Try removing `inhibit_all_warnings!` and see if there are any warning messages that might be relevant, and report back here with a comment.
- Determine which commits CocoaPods is using for Quick and Nimble, and report back here with a comment.

Sorry for the inconvenience, @sundeepgupta! Since Travis CI can't build Swift 1.2 code, it's hard to make absolutely sure what's a bug and what's a derived data issue. :cry:

**Comment by sundeepgupta** [comment]
I believe the derived data clean is what made it work again. I usually do that with any weird Xcode things, but maybe I forgot to last night. 

Thanks for your help! 

Sundeep

**Comment by modocache** [comment]
Awesome, thanks! :100:
