### ISSUE TITLE
Individual test run button is missing

### ISSUE THREAD

**Issue by evgenyneu** [Quick/Quick#293]
## How to reproduce

Call the `it` function:

```
it("my test") {
   expect(3) == 3
}
```
## Expected behaviour

A button appears on the left from the test function. The button can be clicked to run this individual test. The button's color indicates if the test passed.

![xctest](https://cloud.githubusercontent.com/assets/880411/7529385/dcea82fa-f57a-11e4-8d84-97c92805b3e5.png)
## Actual behaviour

The button for the `it` function is missing.

![quick](https://cloud.githubusercontent.com/assets/880411/7529386/e18dd8ac-f57a-11e4-8004-3b7246cdcdd0.png)
## Xcode version

Version 6.4 (6E14)

**Comment by modocache** [comment]
Thanks for the :beetle: report, @evgenyneu! 

I believe this is, unfortunately, a limitation in how Xcode implements this feature. As far as I know, since these buttons were introduced in Xcode 5, they've never worked with [dynamic test invocations](https://github.com/Quick/Quick/blob/f614fdfd6d88de9b456fb479e5ec495791a69d11/Quick/QuickSpec.m#L54), which frameworks like [Quick](https://github.com/Quick/Quick), [Specta](https://github.com/specta/specta), and [Kiwi](https://github.com/kiwi-bdd/Kiwi) use.

I'll keep this issue open for now, as a reminder to file a radar. I'd like to figure out the best way to bring this to the XCTest team's attention--I'm not sure if they'd be willing to grok how Quick works in order to diagnose and solve the problem.

Until this is fixed, I'd recommend running single examples by using `fit`:

```swift
fit("update value") {
  // ...
}
```

This runs just the "focused" example, and none of the others in the test suite.

**Comment by istx25** [comment]
Any developments on this?

**Comment by jeffh** [comment]
Unfortunately Xcode's lockdown of the plugin system has made the work I have on this useless. It's probably better to sunset this. It's Xcode tightly integrating with XCTest that we can't control.
