### ISSUE TITLE
Is there a mocking framework being built for Quick?

### ISSUE THREAD

**Issue by ceeK** [Quick/Quick#297]
Would love to have one for edge cases where my Swift mocks aren't powerful enough:
* Overriding class methods (need to method swizzle)
* Mocking UIApplication (can't have two UIApplications in one app, so can't subclass a mock)

I'm sure there're more.

**Comment by jeffh** [comment]
Hey @ceeK,

Could you elaborate on this more?

I'm just assuming that OCMock solves the problem well enough and Swift doesn't fully support any reflection/swizzling-like APIs yet for Quick to do something (yet). But if you think there are some wins that could be made I'm all ears.

**Comment by ceeK** [comment]
Hey @jeffh,

I've been reluctant to use OCMock given their webpage (http://ocmock.org/swift/) and the limitations they mention. Specifically, all tests must be written in Objective-C. Maybe I've misunderstood, is this really the case? If not, Quick can be used in Objective-C, but I'd much rather use Swift for readability. 

The two issues I mentioned have been a bit annoying to work around. 

For the first issue, I need to override a class method (say, `canSendText() -> Bool`), to return a fixed value. I can't do this with subclassing / extensions. The two ways are to either create a public wrapper function:

```swift
// For testing purposes only.
func canSendText() -> Bool {
    return MFMessageComposeViewController.canSendText()
}
```

Or, I've also had success using Obj-C swizzling APIs in Swift (using this as a guideline: http://nshipster.com/swift-objc-runtime/). The first solution unnecessarily creates a public method (with no `protected` access control being in Swift). The second works too, but I'm wondering why OCMock states not to run in Swift if this is the case?

Apologies if I'm out of my depth here - theres very little I've found online for the details on mocking in Swift.

**Comment by jeffh** [comment]
I'd personally rather use [adapters](http://realm.io/news/testing-in-swift/) when possible. So public wrappers aren't too bad IMO :smile: 

It's possible to leverage the Objective-C Runtime APIs, but there currently would be a lot of sacrifices to make:

- **No Swift-native type support**. Only Obj-C based ones can be mocked. This creates some extra support burden. As much as I love answering the same questions :smiley:, it's preferred to avoid unnecessary pitfalls for users. This means it's generally better to avoid having this feature until a more comprehensive solution can be built.
- **No type checking** (everything would probably need to be `Any` or `NSObject` type). This would make the DSL pretty verbose (with all the type-casts) and probably more limited than an ObjC-native version. I wouldn't be surprised if writing mocks were longer in Swift than in Objective-C because of this.
- There's no `NSInvocation` type in Swift, which enables OCMock's concise DSL.

I can be very wrong about the current landscape, but I haven't seen (or been told) all these points are resolved yet.

Note: Also, it should be possible to override the an objective-c class' method by swizzling the class' metaclass. It might be something using `MFMessageComposeViewController.dynamicType`, but I don't quite remember.

**Comment by modocache** [comment]
I totally agree with @jeffh. I've also seen a few frameworks, like [rheinfabrik/Dobby](https://github.com/rheinfabrik/Dobby), but haven't had the chance to evaluate any of them. There's only so much they can do considering the language really isn't built for this sort of thing.

**Comment by modocache** [comment]
This is an interesting question and discussion, but ultimately this isn't something we'll be implementing as a part of Quick, so I'm closing this issue. Thanks, @ceeK! :+1:
