### ISSUE TITLE
[Idea] Better specs

### ISSUE THREAD

**Issue by marciok** [Quick/Quick#307]
Wouldn't be nice to have fork from [betterspecs](http://betterspecs.org/) on Quick organisation and add as reference on the documentation ? or even create something like betterswiftspecs.org ?   

I think it would be very helpful specially for those whom have never wrote a spec.

**Comment by jeffh** [comment]
It's an idea I like a lot, but it's really hard to agree on what's good form. (For example, I strongly disagree with "How to describe your methods" of betterspecs). As with production code, testing is largely dependent on a team's familiarity with testing.

Best practices always varies by team. What's more familiar with the team's expectations. Betterspecs is almost the complete opposite of what the jasmine team does. Neither is wrong, but they're tradeoffs to the flexibility & safety of the test suite.

If we could agree to something like that, then it would be better :+1:, but I'm only hoping that more developers write test their software :smile:.

**Comment by marciok** [comment]
Yes, @jeffh what you said it makes total sense. The idea for me was just to give a reference for beginners, more like a starting point on what good specs are.

I believe: more references == happier developer 😊

Any thoughts  @Quick/contributors ?

**Comment by dmur** [comment]
I think this is a great idea and should exist to help beginners learn the Quick syntax... quickly :sunglasses:.   Best practices are a great way to guide someone into using the syntax of a library to its fullest extent when starting out. Betterspecs certainly helped me learn how to write better rspec tests.  And to @jeffh's point about best practices widely differing with RSpec, this sort of list definitely works best when meant as guidelines rather than rules.

But I don't think it needs to be part of the official docs.  That level of inclusion might lead people to believe it's less guidelines and more rules, even if it's labeled as the former.

**Comment by istx25** [comment]
I'd be interested in getting started with this if anyone else is interested.

**Comment by ikesyo** [comment]
Closing this as part of issue cleanup.
