### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by joshuatbrown** [Quick/Quick#316]
When I look at a project README on GitHub, I almost always see installation instructions. When they're in the README, they're really easy to find and super convenient. Can we add the installation instructions for Quick to the README? I know they're in a separate doc right now, but I'd be happy to help move them unless there's a compelling reason to leave them out of the README.

**Comment by modocache** [comment]
Thanks for the feedback, @joshuatbrown! I don't want to include all of the installation instructions in the README, since there's actually quite a bit--CocoaPods, Carthage, Git submodules, special instructions if you'd like to run Quick on a physical device... how do you feel about 3e226b3 as a compromise? :snail:

**Comment by joshuatbrown** [comment]
Sounds good to me. Thanks!
