### ISSUE TITLE
Let afterEach block or some other user hook know whether example passed

### ISSUE THREAD

**Issue by pcantrell** [Quick/Quick#358]
Use cases:
- Capture log output and print only if test failed. (This is the one that brought me here.)
- Roll up failures for notification / reporting.
- Do cleanup that’s necessary only if spec didn’t reach its conclusion.

Implementation approaches:
- Add a new property to `ExampleMetadata`.
- Add a new `afterEach` closure flavor that accepts a second argument.
- Provide some sort of “test runner” user hook other than `afterEach` to wrap/replace `Example.run()`.

**Comment by jeffh** [comment]
Hey @pcantrell,

The use cases you describe are definitely useful, but I do see those features as test reporters/runners features (aka, replace `Example.run()`).

**Comment by pcantrell** [comment]
Here’s what I ended up doing for Siesta:

https://github.com/bustoutsolutions/siesta/blob/master/Tests/SiestaSpec.swift#L19-L58

2 of the 3 use cases I mentioned above appear in this code:

* suppress log output on success and
* generate a spec report (which [https://bustoutsolutions.github.io/siesta/specs/](looks kind of cool), BTW).

It turns out both these cases are achievable using standard before/after blocks. The nasty bit is having to override `recordFailureWithDescription`. So it’s not even a matter of having to replace `Example.run`!

Should this issue be closed, then? Maybe. Looking at the linked Siesta code, it would certainly clean things up if Quick handled overriding `recordFailureWithDescription` and passed the failure count to afterEach in metadata. That would also help keep Quick specs from becoming too tightly coupled to XCTest and its implementation details.

Not strictly essential, though.

**Comment by jeffh** [comment]
Thanks for following up @pcantrell,

I'll close this issue be sure to include this feature (test reporters) for #385. The decoupling from XCTest will be the forcing hand.

And I agree, your spec report looks pretty snazzy :+1:

**Comment by modocache** [comment]
I am actually not opposed to threading this information through the metadata; RSpec itself [does so](https://github.com/rspec/rspec-core/blob/c7a05e081f3389e08af24247b5f2c88f6947af1b/lib/rspec/core/example.rb#L493-L494) via [a key called "execution result"](https://github.com/rspec/rspec-core/blob/c7a05e081f3389e08af24247b5f2c88f6947af1b/lib/rspec/core/metadata.rb#L124).

So while this particular use case would indeed be better served by a dedicated reporter infrastructure, this, we could enable it in the time being by including the run result in the example metadata.

Pull requests are always welcome, of course! :grin: I'll also try to build this myself if time allows.

Let me know if you disagree, @jeffh! Otherwise I'll keep this issue open.

**Comment by jeffh** [comment]
I'm not a big fan of the feature. But if you are willing to revert this feature when reporters land. I'll be ok for it for now.




—

**Comment by istx25** [comment]
Seems like this issue went inactive without any direction being taken. Closing for now but we can reopen it in the future if need be.

**Comment by modocache** [comment]
I still think this is a good idea, but I don't have time to implement it 😁
