### ISSUE TITLE
Allow expect() to accept an Observable using push semantics (rather than the current pull)

### ISSUE THREAD

**Issue by DanielAsher** [Quick/Quick#365]
Using `expect` is difficult from 'reactive' types. 

`expect(observable).toEventually(equal(6), timeout: 2)`

would be expressive syntax. how could I go about hooking this up?

**Comment by jeffh** [comment]
What do you mean by reactive types? As a person who hasn't really used that in swift, I'm not entirely sure what you mean.

**Comment by DanielAsher** [comment]
@jeffh hi!

https://github.com/ReactiveX/RxSwift 

is the swift implementation 

of http://reactivex.io/

The core type is `Observable` and all reactive power flows from it.

I've posted a comment to an issue here: 
https://github.com/Quick/Quick/issues/364#issuecomment-134931461

**Comment by jeffh** [comment]
I thought that I might of missed something in the standard core lib.
I understand the concepts of `Observable`, but I don't think this can be in Nimble itself due to the dependency on a reactive library like `RxSwift`.

That being said, it definitely possible to create an adapter library that provides the integration you're looking for.

**Comment by DanielAsher** [comment]
Right. So we need `Observable` / `Observer` protocols in the standard library. that's probably no more than a 10-line fix - _Lattner, are you listening?_ - but will have to wait.

I did find this in the meantime: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/6c37b5ef416799a3a2a61ff78f051d5deb0d76b2/ReactiveCocoaTests/Swift/SignalProducerNimbleMatchers.swift

**Comment by DanielAsher** [comment]
@jeffh thanks for the response.
To continue... I've been using beforeEach so:
```
let newApp = 
    beforeEach { 
        return App() 
    }
```
I feel this better expresses intention and leverages type inference.
I believe some thought should be given to this type of usage. If it already has, please post a link :)

`beforeEach` has the following sketched implementation:
```
public func beforeEach<T>(closure: () -> T) -> Variable<T?> {
    
    let result = Variable<T?>(nil)
    
    let untypedWrapperClosure = { () -> Void in
        let value = closure()
        result.next(value)
    }
    
    beforeEach(untypedWrapperClosure)
    
    return result
}
```

**Comment by DanielAsher** [comment]
@jeffh hi again. 

Reading your response certainly gives me more insight, however, I'm not sure why you say:
> _While it's technically a shared mutable variable,_ 
> _the use of beforeEach effectively clears it's state._

I agree having `value = "modified"` directly preceed `done()` does effectively clear its state, but there is nothing guaranteeing this in more complex, real-world *arrange* steps.

By having `beforeEach` return a value, we add an extra layer of compiler checks.

I may misunderstand how `beforeEach` works, however, and hope you are gentle with the aporias in my thinking :)

**Comment by DanielAsher** [comment]
@jeffh I'd also add that I'm not sure I agree with:

> _While monads are a versatile, expressive construct, they also add conceptual_ 
> _overhead with little gain to what a mutable variable satisfies for most users here._

As an example the `?'` / `!` swift language feature add a monadic security that is unimportant within the body of (normal sized!) function, but is *so very useful* in managing stateful interactions.

Perhaps difference of opinion is based on _unit vs. functional_ testing requirements. Functional testing requires much more complex arrange stages and sequences of expectations.

Would be nice for `Quick` to support these scenarios :)

**Comment by jeffh** [comment]
Hey @DanielAsher,

> To continue... I've been using beforeEach so:

Your `beforeEach` example is effectively a `let` declaration that just happens to be wrapped in a signal (or a cell). While the paradigm is useful, I still think a separate library (or libraries) can provide this feature. It can be more applicable than in the context of testing.

> I agree having value = "modified" directly preceed done() does effectively clear its state, but there is nothing guaranteeing this in more complex, real-world arrange steps.

I see where we're misunderstanding each other. I'll explain my original reasoning:

In the current implementation of Quick, each example (`it`) runs every "parent" `beforeEach` block. Since each variable definition is in a `describe` or `context`, the variables are stored in the scope of those closures. `it` and `beforeEach` strongly retain these contexts when executing, but since each example calls the `beforeEach` closures, the shared mutable values are "reset" to whatever is assigned in those closures between tests, practically isolating shared variables across tests. This leaves Quick the future potential to add parallel tests without change for the user. (In the other issue's example, `afterEach` isn't required.)

Correct me if I'm wrong, but I think you're saying that creating the shared scope within the same test what you're fighting against. I just don't see as strongly that Quick needs to inherit the complexity of building a reactive library or pulling one into core. And since Swift isn't strictly enforcing functional programming, there are still no guarantees about properly managing state, since the test writer can do any nefarious means. It's all gradients about how much enforcement you want.

> By having beforeEach return a value, we add an extra layer of compiler checks.

Even with the extra layers of compiler checks, Swift's compiler currently currently has some hiccups on Nimble's generic-heavy system. As a maintainer, I'd rather defer to the future until the type checker stabilizes.

> As an example the ? / ! swift language feature adds a monadic security that is unimportant within the body of (normal sized!) function, but is so very useful in managing stateful interactions.

For optionals, that makes sense. I never said it was never useful. It's also something that Quick doesn't provide, and I don't think it would be something Quick should provide if Swift stdlib didn't provide it.

> Perhaps difference of opinion is based on unit vs. functional testing requirements. Functional testing requires much more complex arrange stages and sequences of expectations.

For functional/integration testing, it's much more difficult to provide tooling without forcing an opinion that Quick isn't quite ready to provide at this point because it's broader, harder-to-generalize patterns. FRP is one style; others like a pure hidden-mutation based approach for a different notion of readability (eg - WebDriver-style, rspec-rails); or an english syntax (aka - Cucumber); others prefer their programs built an free-interpreter pattern that makes high-level testing still just like testing pure functions.

For better or worse, some people in each camp of testing style view other methods as better/worse. But they're mostly just different attempts at a solution to the same problem.

> Would be nice for Quick to support these scenarios :)

Yes, Quick currently doesn't provide a well-supported system for any of the approaches. Voting for one method over another is something I haven't really spent significant amount of time investigating to be honest. That being said, Quick doesn't stop you from building/attaching one of these patterns on top of it. The current broad goal for Quick is to encourage proper unit testing practices for Swift, which historically has been lacking in the Objective-C community. Once we have a better adoption of that, we can talk about functional/integration tests.

P.S. I rather avoid using the term functional tests, since a very ambiguous word in the context of testing.

**Comment by jeffh** [comment]
While this discussion is all fun. Back to the issue at hand, I roughly run through a few questions when evaluating. I don't think has them all:

- **Is this feature generally useful?** Yes.
- **Is this feature only useful in the context of testing?** Doesn't seem like it, probably better as independent library, like `RxSwift` with an adapter library of some sort.
- **Does this feature prevent future desirable features?** Nope, AFAIK.
- **Is this feature a slippery-slope for related features that are less desirable?** Unknown. Although probably not.
- **What is the maintenance support look like for this feature?** Medium risk - depends on how many are familiar with reactive concepts. Most likely requires answering them on issues for misunderstandings and improper use (like creating the signal not in `beforeEach` or forgetting to cleanup). If adding a dependency, it means making sure it's up to date, but doesn't conflict with other users of the library. Medium-low risk for breaking because of Swift compiler changes. Probably a lot more feature requests related to supporting the reactive infrastructure.
- **Does this improve how people write tests?** A little. Arguably less mutation in tests, but also less stateful applications can do that too; doesn't stop testers from doing variable mutation.
- **Is this a big change? How so?** Mostly additional code - either requires building reactive infrastructure or pulling in a third party library.

**Comment by DanielAsher** [comment]
@jeffh thanks for your detailed comments here. I appreciate the insight into your process.
:8ball: 

It seems that until the `ObservableType` protocol becomes part of the standard library - _Lattner ?_ - interoperability with push data will remain fragmented on iOS/Cocoa. Not a substantive problem for the talented individual developer, but a hurdle none the less.
