### ISSUE TITLE
Tagging better than fitting?

### ISSUE THREAD

**Issue by zbeckman** [Quick/Quick#374]
One feature I absolutely love about specs2 (Scala) is that I can `tag` specific tests, and then I can execute only those tests that I want, based on the tags. Tagging is simple (and you can add multiple tags to a test):

```
tag("destructive", "rest")
it("does something that alters the real database") {
...
```

Then, I could execute tests that are tagged with "destructive" only when I specifically want to:

```
~test-only -- include destructive
```

I use tags to differentiate between "simple" tests, tests for "qa," tests that actually hit our real database versus "mock" tests, and things like that. Super easy to make a small collection of tests that only test my data structures, and run through them all... or switch strides, and ping real web services.

I have no idea how this could be done in Quick with Xcode (given the execution framework). But it sure would be a welcome feature... (in the meantime, we can use `fit` but... it's not as flexible).

Another workflow I follow is to `tag("x")` tests that I'm working on right now – maybe tests that need to be refactored. Then I can run a random collection of tests (whatever is tagged "x") and basically focus my work in a specific area. This is pretty much like using `fit` but strikes me as a tiny bit more flexible, since I don't have to go in and change `it` to `fit` and back again...

**Comment by jeffh** [comment]
Hey @zbeckman,

I like this idea, but I'm not sure how it can be implemented in the current Xcode infrastructure. The conventional method of achieving this is to create separate test bundles, mostly because code inside test bundles can't read much external input (command line args, env variables, etc.).

As a hacky workaround, there's `QuickConfiguration`, but that's basically adding more source code to modify how the test executes. And it certainly doesn't allow a CI to easily control how to run the tests.

**Comment by istx25** [comment]
Is this something we would still like to pursue? @jeffh

**Comment by jeffh** [comment]
I wouldn't, there isn't any way to pass data through XCTest (env, args, etc.). Closing.
