### ISSUE TITLE
Add xctool-based CI step

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#389]
I don't personally use xctool, but some of our users do; see #388. Our CI step should verify that Quick works with the latest version of xctool.

**Comment by mokagio** [comment]
I sarted looking at this, https://github.com/mokagio/Quick/tree/mokagio/test-xctool https://circleci.com/gh/mokagio/Quick.

**Comment by mokagio** [comment]
The work on #417, which is no merged into master, allows to run iOS tests via xctool. Unfortunately there is currently [an xctool issue](https://github.com/mokagio/Quick/commit/e0305a2c0b9ec94fd3ce25c7b69bb7ca90ebc6d8) that prevents running the OS X tests.

Imo this issue should stay open till the OS X tests are running as well.

**Comment by mokagio** [comment]
This issue can now be closed 😉

**Comment by mokagio** [comment]
I think this issue could be closed.

c9767ff975eb4f55d7b9c8725c5b04300849e739 has removed xctool because:

> xctool won't support Xcode 8 and will be deprecated.

I had heard similar news, and later heard that support for Xcode 8 will arrive, although I don't have any link/tweet to reference for it.

Looking at the repo it seems like some Xcode 8 work is on it's way ([this](https://github.com/facebook/xctool/commit/b8bb63a8596399542d10b82e075b5785a40ffd7b) and [this](https://github.com/facebook/xctool/commit/510e366a67a0434c36c8d8e61e467d57d9c153c9) for example).

I do feel that the popularity of xctool has gone down in the past year or so, and don't see much value in having our CI run through it.

**Comment by istx25** [comment]
I agree!
