### ISSUE TITLE
Warnings when building for iOS with Carthage

### ISSUE THREAD

**Issue by brow** [Quick/Quick#424]
When I build Quick using Carthage, I get some warnings:
```
ios $ carthage version
0.10.0
ios $ carthage bootstrap --platform iOS --no-use-binaries
*** Checking out Quick at "v0.8.0"
*** xcodebuild output can be found in /var/folders/m3/0g6_fk1n1pqb2kfq256zdwrw0000gp/T/carthage-xcodebuild.fF1LHc.log
*** Building scheme "Quick-iOS" in Quick.xcworkspace
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```

I suppose this is because the deployment target for Quick's iOS target is 7.0. I can't think of a way for Quick to avoid this warning while maintaining support for iOS 7, but I thought I'd raise the issue.

**Comment by jeffh** [comment]
Hey @brow,

Yeah, this a sucky warning, but we still have users that still report that Quick does work with iOS 7 if the deployment target is set back to that version. Since it's a relatively small change (albeit, annoying warnings), to support iOS 7 deployments, it's worth keeping around for now.

We're aware of the issue, but there's really not a good solution. Thanks for filing this as an issue @brow, I'll be closing this issue because it probably won't change for now (perhaps the next iOS release).

**Comment by brow** [comment]
Good to know. Thanks!
