### ISSUE TITLE
Missing image in documentation

### ISSUE THREAD

**Issue by beny** [Quick/Quick#457]
There is missing image in [docs](https://github.com/Quick/Quick/blob/master/Documentation/BehavioralTesting.md). The links goes [here](http://cl.ly/image/0G2s3B3d2F3O/Screen%20Shot%202015-02-23%20at%204.07.32%20PM.png) on Cloud App but the image does not exists anymore there.

**Comment by jeffh** [comment]
@modocache: Do you know what image was there originally?

**Comment by modocache** [comment]
Hmm, that stinks. I checked my Cloud App uploads but it looks like that image is completely gone. Should have put it in https://github.com/Quick/Assets.

I imagine it was something like the following, except for the failure being described in that section of the documentation:

<img width="380" alt="screen shot 2015-02-26 at 9 08 27 am" src="https://cloud.githubusercontent.com/assets/552921/12790789/064e60a4-ca72-11e5-9b9b-03d8a8a2dae9.png">

I like the idea of using images, since they're friendlier and easier to read. They do have the downside of being hard to maintain, though...

I'll upload a replacement image for this soon. Thanks for the issue, @beny! :+1:

**Comment by takecian** [comment]
I took screenshot for this and uploaded under https://github.com/Quick/Assets/Screenshots .

![](https://raw.githubusercontent.com/Quick/Assets/master/Screenshots/Screenshot_database_size_fail.png)

I will modify document.

**Comment by takecian** [comment]
i send PR(#489)
