### ISSUE TITLE
Wrong error message when using haveCount()

### ISSUE THREAD

**Issue by jschmid** [Quick/Quick#468]
I could not find a commit related to this bug in the unreleased commits, nor an existing issue. I am using Quick 0.8.0.

I have this test:

    allConversations.startWithNext { conversations in
        expect(conversations).to(haveCount(1))
        done()
    }

If in this case the `conversations` array has **zero** elements, the error shown is:

> Assertions: failed - expected to have [] with count 0, got 1

It should be the reverse.

**Comment by briancroom** [comment]
Hey @jschmid, thanks for the report, sorry to hear you're having trouble. Could you verify which version of Nimble you are using? The haveCount matcher is technically a Nimble component rather than a Quick one. 

Additionally, it would be helpful if you could throw up a complete test case that reproduces the issue into a gist. I have verified that the basic behavior of the matcher is correct by looking at the Nimble test suite which is passing:

https://github.com/Quick/Nimble/blob/master/Sources/NimbleTests/Matchers/HaveCountTest.swift

Thanks!

**Comment by jschmid** [comment]
Wow, I trusted that I had the latest versions, but actually I did not.
The release note from Nimble 3.0 states:

> fix haveCount matcher's expected and actual values reversed in expectation message

Sorry about that :relieved:
