### ISSUE TITLE
Use of undeclared identifier 'Filter' on focused tests

### ISSUE THREAD

**Issue by dbarden** [Quick/Quick#470]
Hi all,

Does anybody have a problem running focused test with Objective-C? I'm getting the following:
<img width="698" alt="screenshot 2016-01-29 05 34 03" src="https://cloud.githubusercontent.com/assets/104456/12667333/651716f2-c64a-11e5-8712-7d76ab4e9812.png">

I'm running Quick v0.9.0 integrated via CocoaPods and the whole file can be seen [here](https://github.com/dbarden/testQuick/blob/master/testQuickTests/DBANoteSpec.m)

Thanks,

**Comment by morganchen12** [comment]
If you change the import statement at the top from `#import <Quick/Quick.h>` to `@import Quick;` do the errors go away?

This is kind of a zero-effort shot in the dark, so it might not work--if it still flags build errors I can take a closer look.

**Comment by briancroom** [comment]
I think @morganchen12 has provided a good workaround for this issue. 

I'm observing the same issue as @dbarden with Quick's own FocusedTests spec, however it's just the editor showing the error. The file ends up building just fine, presumably because Clang turns the #import directive into an @import statement internally when modules are enabled for the build. 

I'm thinking this is effectively an Xcode bug, where symbols from the generated -Swift.h header aren't being made available to the editor.

**Comment by dbarden** [comment]
Yeap, that fixes. Thanks a lot :)

It still presents the problem that @briancroom describes.

I'll take at the other problem to understand it a bit better, but now at least I have a way to run a focused test. Based on that, I'm closing the ticket.
