### ISSUE TITLE
Question about "expect" outside of "it"

### ISSUE THREAD

**Issue by derpoliuk** [Quick/Quick#508]
I want to apologize in advance if I'm missing something fundamental in this issue.

I'm running Unit Tests in Xcode 7.3, Nimble v3.2.0 and Quick v0.9.1.

**TL;DR:** When I use `expect` outside of `it` - test throws exception. Is it expected behavior, because exception description doesn't say so (`An 'expect(...).to' expectation was evaluated outside of an 'it', 'context', or 'describe' block`)?

**Long version:**

I have following code structure:

```
override func spec() {
    describe("1") {
        // 1
        expect(true).to(beFalse()) // throws an exception
        context("context") {
            // 2
            expect(true).to(beFalse()) // throws an exception
            it("it") {
                expect(true).to(beFalse()) // test is running as expected
            }
        }
    }
}
```
`expect` on line `1` and `2` throws an exeption:

```
An exception occurred when building Quick's example groups.
Some possible reasons this might happen include:

- An 'expect(...).to' expectation was evaluated outside of an 'it',
'context', or 'describe' block [...]
```

My question is: can one use `expect` outside of `it`?

**Comment by lolgear** [comment]
@derpoliuk by design it cannot be done. Well, all rspec-like testing frameworks have a descriptive concept. You can **describe**, for example, `.limit or .where function` in empty `context` with tests like *expected* to be empty or false.

All tests are supposed to be:

*describe* behaviour or variable. in some *context* *it* is *expected* to have positive results.

Or swap context and describe.

in empty *context* *describe* limit function. It is expected to have value not greater than zero.

```
describe(".limit") {
  context("empty") {
    it("is expected to have upper bound as zero") {
      expect(variable.limit).notTo beGreaterThan(0)
    }
  }
}
```

**Comment by derpoliuk** [comment]
@lolgear thank you for detailed explanation, it's very helpful!
