### ISSUE TITLE
Discuss adding analytics

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#571]
**This is a contentious topic, and one we don't have a consensus on, so please don't interpret this as an indication that Quick will add analytics. This is just a discussion.**

Should Quick execute code that sends usage data to maintainers? I had previously thought this was definitely _not_ something Quick should do, but developer tools such as [Homebrew do this](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Analytics.md), which makes me think that there might be something to it.

Usage data would allow us to:
1. Get motivated, by seeing how many people use Quick.
2. Inform our feature/bugfix prioritization.
3. Measure performance optimizations.
4. Provide some interesting data to Apple.

Obviously whatever scheme we decide upon should have a way to opt out of sending data.

This would require quite a bit of organizational work: we'd need to create a Google Analytics account (if that's what we end up using) as well as implement the Quick software that sends analytics data. I think we should also discuss making as much of the analytics data public as we responsibly can.

Thoughts?

**Comment by istx25** [comment]
I'm quite fond of the idea (both as a user of a framework and as a maintainer). The data would have to be anonymised and provide no identifying information (by default). If we open-sourced what data we were collecting, I think everyone would appreciate that feature.

I'm pretty sure Realm does this and I don't mind. It's good to know for stat purposes and knowing how much people use Quick, but also as a way for us to intrinsically collect information about bugs, crashes, etc.

Just my 2 cents. May have more opinions later on.

**Comment by mkauppila** [comment]
Currently, I'm not a big fan of the idea but the more I think about it, the better it seems. I agree with the benefits but having analytics is a really sensitive topic for many people / projects. 

Personally I feel that all the data Quick collects should be generic enough (which might also mean it's useless) that we wouldn't need to anonymize it. A slight error in anonymization might cause a huge PR issues and give negative karma for Quick. Sounds risky to me. 

Open sourcing (as @istx25 mentioned) is a brilliant idea that would bring more transparency and trust into this. Though I feel this all or nothing thing, it's not going to work if only some parts of the analytics data is released.

And lastly, I feel this should be opt-in (not opt-out) feature because that'll prevent the enabled by accident cases where somebody accidentally shares the analytics data without knowing about it.

What sort of data should Quick collect and share?

psst. @modocache the link to the Homebrew's docs seems to be broken (== responce code is 404)

**Comment by ikesyo** [comment]
This is stale, let's close this for now. Feel free to reopen if there is any progress on this.
