### ISSUE TITLE
Documentation in pt-br 🇧🇷

### ISSUE THREAD

**Issue by marciok** [Quick/Quick#610]
Hi,
I think would be great to have the Quick documentation in portuguese. 
There's a big iOS/OSX community in Brazil, and I'm sure if the docs are in portuguese, it could help lots of devs. 
I will have a long flight today, therefore I'm going to use the time to translate. 

Any objections? 
Marcio

**Comment by istx25** [comment]
Go for it! Looking forward to seeing the translated copies. Thanks for doing it!

**Comment by pedrovereza** [comment]
Awesome!

If you need some help, let me know 😉

**Comment by modocache** [comment]
Excellent!! Thanks, @marciok 💓

**Comment by jessesquires** [comment]
Hey there! 👋🏼 

I'm a new maintainer for this project and I'm trying to get the next release out ASAP and also clean up old issues and old PRs. I'm closing all issues that no longer seem relevant or are very old / stale.

This **does not** mean this issue is necessarily being rejected. If you are still interested in contributing the changes specified in this issue, please comment to request it be reopened.

We appreciate you opening this issue and acknowledge the time and effort you put in to contribute! You're awesome. 💯 However, we are all volunteers here with limited capacity working for free. Unfortunately, that means we must close out stale issues and PRs to move the project forward in a reasonable way.

We apologize for the inconvenience and appreciate your understanding! 😎 ✌🏼
