### ISSUE TITLE
Question - Do we need to worry about future support?

### ISSUE THREAD

**Issue by cliren** [Quick/Quick#655]
This is an important question (to the authors and contributors) about adapting Quick as a unit testing framework. We have tried couple of BDD frameworks before and was not satisfied with them and Quick seems more promising in its style and easy of writing. But we are worried that it will be another BDD framework we have to start migrating to a new framework in the future. Do we have assurance from Quick team that they will support future versions of Xcode and Swift? The project will be a bigger risk Quick tests stop working due to an Apple change either in Swift or Xcode that Quick wont' support.

**Comment by morganchen12** [comment]
Quick is an open source project that isn't formally sponsored by anyone (I think), so its continued support is dependent on the free time and willingness of its contributors. BDD frameworks on Apple platforms in the past have especially suffered from XCTest's closed nature, which tends to generate mentally exhausting bugs with impossible repro steps. If you'd like to help ensure Quick stays around, you could take some ownership of maintaining it while using it to test your code :)

As of now I think Quick is in a good spot and will be around for a while, particularly since @istx25 has been doing tons of work.

**Comment by cliren** [comment]
I wish it stays for a long time and I will try to commit time to support once I get familiar with the code base.

**Comment by istx25** [comment]
Aw thanks, @morganchen12!!! ❤️ 💛 💚 And yeah, @cliren, we will do our best to ensure the project stays alive and thrives. It's a community more than anything and I want to ensure our community is always healthy and growing. With that said, it takes more than one or two or whatever amount. If you see a problem, submit a PR and help us fix it. We'll do this all together and make a difference.
