### ISSUE TITLE
How use with swiftPM (macOS and Linux)

### ISSUE THREAD

**Issue by gperdomor** [Quick/Quick#675]
Please update the docs

**Comment by istx25** [comment]
We'd be happy to review a PR. This project is led by community members who contribute to Quick in their free time and things like documentation sometimes go out of date.

**Comment by jessesquires** [comment]
Hey there! 👋🏼 

I'm a new maintainer for this project and I'm trying to get the next release out ASAP and also clean up old issues and old PRs. I'm closing all issues that no longer seem relevant or are very old / stale.

This **does not** mean this issue is necessarily being rejected. If you are still interested in contributing the changes specified in this issue, please comment to request it be reopened.

We appreciate you opening this issue and acknowledge the time and effort you put in to contribute! You're awesome. 💯 However, we are all volunteers here with limited capacity working for free. Unfortunately, that means we must close out stale issues and PRs to move the project forward in a reasonable way.

We apologize for the inconvenience and appreciate your understanding! 😎 ✌🏼
