### ISSUE TITLE
Please publish framework.zip for carthage users.

### ISSUE THREAD

**Issue by soranoba** [Quick/Quick#700]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

For shortening the build time with carthage in the user of this library, you can publish framework.zip to release.
I want you to do this.

sample : https://github.com/erikdoe/ocmock/releases
documents : https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

**Comment by jeffh** [comment]
Hey @soranoba, thanks for filing an issue.

Unfortunately, until Swift reaches ABI stability, it is unsafe to publish a prebuilt framework (see #528). TL;DR:

- Frameworks must use the exact same version of Xcode to compile.
- Because of ABI instability, different machines building frameworks can cause subtle runtime crashes and bugs.

I'm closing this issue until Swift cuts a final release that has that stability

**Comment by soranoba** [comment]
Thank you for answer :smile:
