### ISSUE TITLE
Why Quick uses c99ExtendedIdentifier?

### ISSUE THREAD

**Issue by ManWithBear** [Quick/Quick#929]
I'm playing around with runtime test generation and found that I'm able to create tests with namespaces and punctuation character in method name.
In same time Quick uses `QCKObjCStringUtils.c99ExtendedIdentifier(...)` to remove such characters.
Could you share why it is important?

**Comment by ikesyo** [comment]
There should be a reasoning about this in #652.

**Comment by ManWithBear** [comment]
My bad, it was typo: "with whitespaces and punctuation"

**Comment by ManWithBear** [comment]
@ikesyo thanks for PR link.
If I understand it properly in PR `c99ExtendedIdentifier` used to resolve issue with Quick unable to load bundles containing `-` in name.
I'm asking about using `c99ExtendedIdentifier` when converting description of `it` to method name, here:
https://github.com/Quick/Quick/blob/4a4b6c7dd5aac29e0ea8263d1829de006227f59e/Sources/Quick/QuickSpec.swift#L77

**Comment by ikesyo** [comment]
I linked the pull request because it introduced the `c99ExtendedIdentifier` symbol. What you are interested will be  formerly used `qck_selectorName`: https://github.com/Quick/Quick/pull/652/files#diff-812bf5467da2b680bf7f763480bca555L122

**Comment by ikesyo** [comment]
Looks like the followings are the point

- https://github.com/Quick/Quick/commit/606d77ab12faac00386f24872e33a0347711f0ec
- https://github.com/Quick/Quick/pull/33

**Comment by ManWithBear** [comment]
Wow, thanks for investigation.

@modocache was first to forbid whitespace in method names.
https://github.com/Quick/Quick/blob/606d77ab12faac00386f24872e33a0347711f0ec/Quick/Core/NSString%2BQCKSelectorName.m#L14
What was reason for it?

**Comment by ManWithBear** [comment]
Possible reason:
> A better naming scheme is probably to strip the invalid characters for an identifier or replace them with an _. Historically, Xcode's test browser only accepted function-styled identifier names.
https://github.com/Quick/Quick/pull/295/files/b926240385e3fad363860b8245e7185ee236e1cb#r30872413

Apparently it's not true with latests Xcode 11.

**Comment by ManWithBear** [comment]
Just wanna bump this thread, cauz I'm still interested.

**Comment by jessesquires** [comment]
Hey there! 👋🏼 

I'm a new maintainer for this project and I'm trying to get the next release out ASAP and also clean up old issues and old PRs. I'm closing all issues that no longer seem relevant or are very old / stale.

This **does not** mean this issue is necessarily being rejected. If you are still interested in contributing the changes specified in this issue, please comment to request it be reopened.

We appreciate you opening this issue and acknowledge the time and effort you put in to contribute! You're awesome. 💯 However, we are all volunteers here with limited capacity working for free. Unfortunately, that means we must close out stale issues and PRs to move the project forward in a reasonable way.

We apologize for the inconvenience and appreciate your understanding! 😎 ✌🏼
